name: Test Production Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testAndDeploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm test
      - run: npm run build

      - name: Install Railway
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy
        run: railway up -e production -s tests-E2E

        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
